version: '3'

services:
  server:
    build:
      context: ./server  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - shared_volume:/app
    expose:
      - "8080"

  bankserver:
    build:
      context: ./bankserver 
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - shared_volume:/app
    expose:
      - "8081"

volumes:
  shared_volume:
