version: '3.8'

#services:
#  mongodb:
#    image: 'mongo:latest'
#    container_name: bankserver
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: adminCashManager
#      MONGO_INITDB_ROOT_PASSWORD: adminCashManager

